-- 0. Limpiar (borrar tabla si existe para evitar errores)
drop table if exists games;

-- 1. Crear la tabla de juegos
create table games (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  platform text not null,
  image_url text,
  completed boolean default false
);

-- 2. Habilitar seguridad (RLS)
alter table games enable row level security;

-- 3. Crear políticas de acceso PÚBLICO (para que funcione sin login)

-- Permitir leer (ver los juegos)
create policy "Public Read Access"
  on games for select
  using ( true );

-- Permitir insertar (agregar juegos)
create policy "Public Insert Access"
  on games for insert
  with check ( true );

-- Permitir actualizar (marcar como terminados)
create policy "Public Update Access"
  on games for update
  using ( true );

-- Permitir eliminar (borrar juegos)
create policy "Public Delete Access"
  on games for delete
  using ( true );
